// This file is automatically generated by Flutter. Do not edit manually.
// Replace the firebase configuration with your actual Firebase config

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyWebApiKey123456789',
    appId: '1:123456789:web:abcdef1234567890',
    messagingSenderId: '123456789',
    projectId: 'urbanx-demo',
    authDomain: 'urbanx-demo.firebaseapp.com',
    databaseURL: 'https://urbanx-demo.firebaseio.com',
    storageBucket: 'urbanx-demo.appspot.com',
    measurementId: 'G-DUMMY123456',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDummyAndroidApiKey123456789',
    appId: '1:123456789:android:abcdef1234567890',
    messagingSenderId: '123456789',
    projectId: 'urbanx-demo',
    databaseURL: 'https://urbanx-demo.firebaseio.com',
    storageBucket: 'urbanx-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyIOSApiKey123456789',
    appId: '1:123456789:ios:abcdef1234567890',
    messagingSenderId: '123456789',
    projectId: 'urbanx-demo',
    databaseURL: 'https://urbanx-demo.firebaseio.com',
    storageBucket: 'urbanx-demo.appspot.com',
    iosBundleId: 'com.example.urbanX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyMacOSApiKey123456789',
    appId: '1:123456789:macos:abcdef1234567890',
    messagingSenderId: '123456789',
    projectId: 'urbanx-demo',
    databaseURL: 'https://urbanx-demo.firebaseio.com',
    storageBucket: 'urbanx-demo.appspot.com',
    iosBundleId: 'com.example.urbanX',
  );
}



